package com.spring.cold.pojo;

import com.baomidou.mybatisplus.annotation.TableField;
import org.springframework.stereotype.Repository;

import java.io.Serializable;

@Repository
public class DpUserRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_user_role.user_id
     *
     * @mbggenerated Wed Jun 10 16:48:53 GMT+08:00 2020
     */
    @TableField(value = "user_id")
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_user_role.role_id
     *
     * @mbggenerated Wed Jun 10 16:48:53 GMT+08:00 2020
     */
    @TableField(value = "role_id")
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dp_user_role
     *
     * @mbggenerated Wed Jun 10 16:48:53 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;
    @TableField(exist = false)
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_user_role.user_id
     *
     * @return the value of dp_user_role.user_id
     *
     * @mbggenerated Wed Jun 10 16:48:53 GMT+08:00 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_user_role.user_id
     *
     * @param userId the value for dp_user_role.user_id
     *
     * @mbggenerated Wed Jun 10 16:48:53 GMT+08:00 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_user_role.role_id
     *
     * @return the value of dp_user_role.role_id
     *
     * @mbggenerated Wed Jun 10 16:48:53 GMT+08:00 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_user_role.role_id
     *
     * @param roleId the value for dp_user_role.role_id
     *
     * @mbggenerated Wed Jun 10 16:48:53 GMT+08:00 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_user_role
     *
     * @mbggenerated Wed Jun 10 16:48:53 GMT+08:00 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}